Implementing user testing
mary0L/Hustle-Hamster pull request #83
Opened 2024-10-04 10:17 UTC by winka826

Please have a look over them, especially making sure the wording on the typing toggle makes sense.

2024-10-04 21:29 UTC, arcfernandes04 requested changes
The typing animation option in the menu doesn't really make sense, as it's called "skip typing animation" and when this is "on" the typing animation is on, rather than the skip being on. I just think that it's counter intuitive? Maybe just switch the "(on)" and "(off)" indications around and it should be all good

2024-10-06 09:01 UTC, winka826 commented
> The typing animation option in the menu doesn't really make sense, as it's called "skip typing animation" and when this is "on" the typing animation is on, rather than the skip being on. I just think that it's counter intuitive? Maybe just switch the "(on)" and "(off)" indications around and it should be all good. I also didn't actually see the intro blurb at any point?

I've swapped the typing toggles (I thought I had it right at first but I just confused myself haha). I didn't add a long blurb, just some more writing right at the beginning that mentions its a journaling app (didn't want too much as user can't turn off typing at this point)! Its in the main.cpp line 27 and 28

2024-10-06 09:06 UTC, mary0L approved these changes

2024-10-06 22:58 UTC, arcfernandes04 approved these changes

2024-10-06 22:59 UTC, merged